## class exercise: table

In [19]:
import numpy as np

a = np.arange(10,30).reshape(4, 5)
orange = a[0:1, 0:1]
red = a[0, 1:4]
green = a[0:3, 2]
light_blue = a[0:4, 1:4:2]
dark_blue = a[0:3:2, -1::2]
print(a)
print(orange)
print(red)
print(green)
print(light_blue)
print(dark_blue)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[10]]
[11 12 13]
[12 17 22]
[[11 13]
 [16 18]
 [21 23]
 [26 28]]
[[14]
 [24]]


## class exercise: cube

In [25]:
a = np.arange(0, 27).reshape((3, 3, 3))
a1 = a[1, 1, 0:]
a2 = a[0:, 1, 0]
a3 = a[0, 0:, 2]
print(a1)
print(a2)
print(a3)

[12 13 14]
[ 3 12 21]
[2 5 8]


## class exercise: masking

In [28]:
data = np.arange(1,101).reshape(10,10)
mask = data%2 == 0
print(data[mask])
print(data[np.where(data%10 == 6)])

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[ 6 16 26 36 46 56 66 76 86 96]


In [62]:
filename = '../data/befkbhalderstatkode.csv'

bef_stats_df = np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1)
dd = bef_stats_df
mask2 = (dd[:, 0] == 2015) & (dd[:, 2] == 0) & (dd[: ,3] == 5180)

print(f'2: 0 år gamle tyske børn i københavn: {np.sum(dd[mask2][:, 4])}')

def funktion(aar, bydel, alder, statkode):
    funcmask = (dd[:, 0] == aar) & (dd[:, 1] == bydel) & (dd[: ,2] == alder) & (dd[: , 3] == statkode)
    return dd[funcmask][:, 4]

print(f'3: {funktion(2015, 1, 0, 5180)}')

def funktion2(aar, bydel, alder = None, statkode):
    if alder == None:
        funcmask = (dd[:, 0] == aar) & (dd[:, 1] == bydel) & (dd[: , 3] == statkode)
        return np.sum(dd[funcmask][:, 4])
    funcmask = (dd[:, 0] == aar) & (dd[:, 1] == bydel) & (dd[: ,2] == alder) & (dd[: , 3] == statkode)
    return dd[funcmask][:, 4]
      
print(f'4: {funktion2(aar = 2015, bydel=1, statkode)}')

2: 0 år gamle tyske børn i københavn: 35
3: [3]
